").show();\r\n");
      out.write("        $(\"#folder-nav .hasSelected\").removeClass(\"hasSelected\");\r\n");
      out.write("        $source.addClass(\"hasSelected\");\r\n");
      out.write("        searchObj.orgerFlag = false;//重置排序标志\r\n");
      out.write("        searchObj.filtrate.flag = false;//重置搜索标志\r\n");
      out.write("        //重新初始化图片浏览\r\n");
      out.write("        dummyPhotoviewAuto(\"arctable\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("      }, \"GET\");\r\n");
      out.write("    }\r\n");
      out.write("    var e = window.event;\r\n");
      out.write("    try{\r\n");
      out.write("      e.stopPropagation();\r\n");
      out.write("    }catch(e){}\r\n");
      out.write("  }); */\r\n");
      out.write("\r\n");
      out.write("    $(\"#orderSearchBox span a.order\").click(function() {\r\n");
      out.write("        $(\"#orderSearchBox span a.current\").removeClass(\"current\");\r\n");
      out.write("        $(this).addClass(\"current\");\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(\".filter-button\").click(function() {\r\n");
      out.write("        $(\".filter-button\").parents(\"ul\").find(\"li\").css(\"background-color\",\"\");\r\n");
      out.write("        var filterDiv = $(\".filter-option\");\r\n");
      out.write("        if (filterDiv.hasClass(\"hide\")) {\r\n");
      out.write("            filterDiv.removeClass(\"hide\");\r\n");
      out.write("        } else {\r\n");
      out.write("            filterDiv.addClass(\"hide\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //上传\r\n");
      out.write("    $(\"#actionbar-btn-upload\").click(function() {\r\n");
      out.write("\t    var ownerType = \"10000003\";\r\n");
      out.write("\t    if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isManager}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" == \"true\"){\r\n");
      out.write("\t\t    ownerType = \"10000001\";\r\n");