rite("    //分页\r\n");
      out.write("    function pagination(param) {\r\n");
      out.write("        var dataUrl = $(\".hasSelected\").attr(\"data-url\");\r\n");
      out.write("        if (!param.folderId) {\r\n");
      out.write("            var folderId = $(\".hasSelected\").attr(\"data-files-id\");\r\n");
      out.write("            if(!$.isNumeric(folderId)){\r\n");
      out.write("    \t        folderId = 0;\r\n");
      out.write("            }\r\n");
      out.write("            param.folderId = folderId;\r\n");
      out.write("        }\r\n");
      out.write("        if (searchObj.filtrate.flag) {//搜索分页\r\n");
      out.write("            searchObj.filtrate.search(param.pageIndex);\r\n");
      out.write("        } else if (searchObj.orgerFlag) {\r\n");
      out.write("            searchObj.orderBy(searchObj.orderFiled, param.pageIndex);\r\n");
      out.write("        } else {//未使用搜索的分页\r\n");
      out.write("            if (dataUrl) {\r\n");
      out.write("                $(\"#data-files-list\").loadHtml(top.TC.config.baseUrl + dataUrl, \r\n");
      out.write("                \t\t{\"pageIndex\": param.pageIndex,curMillis: new Date().getMilliseconds()},\r\n");
      out.write("                \t\tfunction() {}, \"GET\");\r\n");
      out.write("            } else {\r\n");
      out.write("                var args = {\r\n");
      out.write("                            \"m\": \"manageFolder\",\r\n");
      out.write("                            \"ownerType\": \"10000001\",\r\n");
      out.write("                            \"pageIndex\": param.pageIndex,\r\n");
      out.write("                            curMillis: new Date().getMilliseconds()\r\n");
      out.write("                           };\r\n");
      out.write("                var viewType = $(\"input[name=viewType]\").val();\r\n");
      out.write("                $(\"#data-files-list\").loadHtml(top.TC.config.baseUrl + \"tc/knowledge/\",\r\n");
      out.write("                \t\t{\r\n");
      out.write("                         \"m\": \"showFolder\",\r\n");
      out.write("                         \"viewType\":viewType,\r\n");
      out.write("                         \"ownerType\": \"10000001\",\r\n");
      out.write("                         \"pageIndex\": param.pageIndex,\r\n");
      out.write("                         \"folderId\": param.folderId,\r\n");
      out.write("                         curMillis: new Date().getMilliseconds()\r\n");
      out.write("                         }, \r\n");
      out.write("                         function() {\r\n");
      out.write("                \t         //再次初始化图片浏览\r\n");
      out.write("                \t         dummyPhotoviewAuto(\"arctable\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("                         },\"GET\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function openTask(title, id) {\r\n");
      out.write("        TC.ui.openResource({\r\n");
      out.write("            id: \"tc/task/\" + id + \"/\",\r\n");
      out.write("            label: title,\r\n");
      out.write("            url: \"tc/task/\" + id + \"/\",\r\n");
      out.write("            icon: \"\"\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("\t \t$(\"#allFold span\").click(function(){\r\n");
      out.write("\t \t\t$(this).toggleClass(\"glyphicon-chevron-down glyphicon-chevron-right\");\r\n");
      out.write("\t\t\t$(this).parents().next(\"ul\").toggle();\r\n");
      out.write("    \t});\r\n");
      out.write("\t});\r\n");
      out.write("    $(\".order-box .links\").click(function() {\r\n");
      out.write("    $(\".order-box .links\").removeClass(\"choosed\");\r\n");
      out.write("        $(this).addClass(\"choosed\");\r\n");
      out.write("    });\r\n");
      out.write("    var searchObj = {\r\n");
      out.write("\t    orderFiled: \"createDate\",//mostDownload|lastUpload|highMostAppraise\r\n");
      out.write("\t    folderId: 0,\r\n");
      out.write("\t    orgerFlag: false,\r\n");
      out.write("\t    orderBy: function(field, pageIndex, source) {\r\n");
      out.write("\t\t\tif (source) {\r\n");
      out.write("\t\t\t    source.parent().parent(\"ul\").find(\"li\").css(\"background-color\",\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (field && \"string\" === $.type(field)) {\r\n");
      out.write("\t\t\t    this.orderFiled = field;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("            pageIndex = pageIndex || 1;\r\n");
      out.write("            this.filtrate.updateTitle($(\"input[name='title']\").val());\r\n");
      out.write("            var args = {\r\n");
      out.write("                        \"folderId\": this.folderId,\r\n");
      out.write("\t\t\t\t         \"searchType\": \"orderBy\",\r\n");
      out.write("\t\t\t\t         \"orderFiled\": this.orderFiled,\r\n");
      out.write("\t\t\t\t         \"ownerType\": \"10000001\",\r\n");
      out.write("\t\t\t\t         \"title\":this.filtrate.title,\r\n");
      out.write("\t\t\t\t         \"m\": \"search\",\r\n");
      out.write("\t\t\t\t         \"pageIndex\": pageIndex\r\n");
      out.write("                        };\r\n");
      out.write("\t\t\tthis.search(args);\r\n");
      out.write("\t\t\tsearchObj.orgerFlag = true;\r\n");
      out.write("\t\t\tsearchObj.filtrate.flag = false;\r\n");
      out.write("        },\r\n");
      out.write("        filtrate: {\r\n");
      out.write("            flag: false,\r\n");
      out.write("            title: null,\r\n");
      out.write("            freeLevel: null,\r\n");
      out.write("            fromScore: null,\r\n");
      out.write("            endScore: null,\r\n");
      out.write("            dateFrom: null,\r\n");
      out.write("            dateTo: null,\r\n");
      out.write("            updateTitle:function(text){\r\n");
      out.write("            \tif ($.type(text) === \"string\") {\r\n");
      out.write("\t                text = $.trim(text);\r\n");
      out.write("\t                if (!/^\\s*$/.test(text)) {\r\n");
      out.write("\t                \tthis.title = text;\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("            },\r\n");
      out.write("            byTitle: function(titleBox) {\r\n");
      out.write("\t            this.title = null;\r\n");
      out.write("\t            this.updateTitle($(titleBox).val());\r\n");
      out.write("\t            this.search(1);\r\n");
      out.write("            },\r\n");
      out.write("            byDateRange: function(range) {\r\n");
      out.